-- Insert sample marketplace opportunities
INSERT INTO marketplace_opportunities (
    title,
    description,
    budget,
    required_skills,
    estimated_duration,
    status,
    category,
    location,
    experience_level,
    project_type,
    is_featured,
    views_count,
    applications_count
) VALUES 
(
    'AI-Powered E-commerce Platform Development',
    'Looking for an experienced team to build a modern e-commerce platform with AI-powered product recommendations and personalized shopping experiences. The platform should include features like real-time inventory management, multi-vendor support, and advanced analytics dashboard.',
    75000.00,
    ARRAY['React', 'Node.js', 'Python', 'TensorFlow', 'PostgreSQL', 'AWS'],
    '6-8 months',
    'open',
    'Web Development',
    'Remote',
    'Expert',
    'Full Stack',
    true,
    150,
    12
),
(
    'Mobile App for Fitness Tracking',
    'Need a mobile app developer to create a cross-platform fitness tracking application. The app should include features like workout planning, progress tracking, social sharing, and integration with popular fitness devices.',
    45000.00,
    ARRAY['React Native', 'Firebase', 'Node.js', 'MongoDB'],
    '4-6 months',
    'open',
    'Mobile Development',
    'Remote',
    'Intermediate',
    'Mobile App',
    true,
    120,
    8
),
(
    'Blockchain-Based Supply Chain Solution',
    'Seeking a blockchain expert to develop a supply chain tracking system using smart contracts. The solution should provide real-time tracking, transparency, and automated compliance checks.',
    95000.00,
    ARRAY['Solidity', 'Web3.js', 'Node.js', 'Ethereum', 'React'],
    '8-10 months',
    'open',
    'Blockchain',
    'Remote',
    'Expert',
    'Blockchain',
    true,
    180,
    15
),
(
    'UI/UX Design for SaaS Dashboard',
    'Looking for a UI/UX designer to create a modern and intuitive dashboard interface for our SaaS product. The design should focus on user experience and include responsive layouts for all devices.',
    35000.00,
    ARRAY['Figma', 'UI/UX Design', 'Prototyping', 'User Research'],
    '3-4 months',
    'open',
    'Design',
    'Remote',
    'Intermediate',
    'UI/UX Design',
    false,
    90,
    6
),
(
    'Machine Learning Model for Predictive Analytics',
    'Need a data scientist to develop and implement a machine learning model for predictive analytics in the financial sector. The model should analyze historical data to predict market trends.',
    85000.00,
    ARRAY['Python', 'TensorFlow', 'Pandas', 'Scikit-learn', 'SQL'],
    '6-7 months',
    'open',
    'AI/ML',
    'Remote',
    'Expert',
    'Machine Learning',
    true,
    160,
    10
),
(
    'WordPress Theme Development',
    'Seeking a WordPress developer to create a custom theme for an educational platform. The theme should be optimized for performance and include features like course management and student progress tracking.',
    25000.00,
    ARRAY['WordPress', 'PHP', 'JavaScript', 'CSS', 'MySQL'],
    '2-3 months',
    'open',
    'Web Development',
    'Remote',
    'Intermediate',
    'WordPress',
    false,
    70,
    4
),
(
    'Cloud Migration Project',
    'Looking for a cloud architect to help migrate our existing infrastructure to AWS. The project involves setting up microservices architecture and implementing CI/CD pipelines.',
    65000.00,
    ARRAY['AWS', 'Docker', 'Kubernetes', 'Terraform', 'Jenkins'],
    '4-5 months',
    'open',
    'DevOps',
    'Remote',
    'Expert',
    'Cloud',
    true,
    140,
    9
),
(
    'Content Management System Development',
    'Need a full-stack developer to build a custom CMS for a media company. The system should handle content creation, publishing workflows, and media management.',
    55000.00,
    ARRAY['React', 'Node.js', 'MongoDB', 'Express', 'TypeScript'],
    '5-6 months',
    'open',
    'Web Development',
    'Remote',
    'Intermediate',
    'Full Stack',
    false,
    100,
    7
); 